export interface Setting {
    id: number,
    fqdn: string,
    dualCerts: boolean,
    minPort: number,
    maxPort: number,
    DNSServers: string,
    ipv4: string,
    ipv6: string,
    arch: string,
    concurrentBuilds: number,
    applicationStoragePathMigrationFinished: boolean,
    numberOfDockerImagesKeptLocally: number,
    proxyDefaultRedirect: string,
    doNotTrack: boolean,
    sentryDSN: string,
    previewSeparator: string,
    isAPIDebuggingEnabled: boolean,
    isRegistrationEnabled: boolean,
    isAutoUpdateEnabled: boolean,
    isDNSCheckEnabled: boolean,
    isTraefikUsed: boolean,
    createdAt: Date,
    updatedAt: Date
}